# Generated by Django 2.2.1 on 2019-07-18 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('token', models.CharField(max_length=150, null=True)),
                ('password', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('shop_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('token', models.CharField(max_length=150, null=True)),
                ('password', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fruit_name', models.CharField(max_length=255)),
                ('weight', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('price', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=1000)),
                ('farm_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('farm_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('province', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tabafi.Farmer')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fruit_name', models.CharField(max_length=255)),
                ('weight', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('description', models.CharField(max_length=1000)),
                ('customer_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('customer_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('province', models.CharField(default=None, max_length=30)),
                ('city', models.CharField(default=None, max_length=30)),
                ('address', models.CharField(default=None, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='tabafi.Customer')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tabafi.Product')),
            ],
        ),
    ]
