# Generated by Django 2.2.1 on 2019-05-28 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('token', models.CharField(max_length=150, null=True)),
                ('password', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('shop_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('token', models.CharField(max_length=150, null=True)),
                ('password', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('weight', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=20, max_digits=20)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fruit_type', models.CharField(max_length=255)),
                ('ordered_weight', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('farmer_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('farmer_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('customer_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('customer_lng', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='FruitImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabafi.Fruit')),
            ],
        ),
    ]
