# Generated by Django 2.2.1 on 2019-08-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabafi', '0002_auto_20190812_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='created_at',
            field=models.DateTimeField(default='2019-08-12 16:00:43'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='updated_at',
            field=models.DateTimeField(default='2019-08-12 16:00:43'),
        ),
    ]
